<?php
/** index Controler class generated by Prologics framework **/

class index extends controller {

    function __construct() {
        parent::__construct();
    }

    function index() {
        $this->view->load('index/index');
    }   
    function loginDo(){
    	//echo "PHP version ".phpversion()."<br/>";
    	$this->model->loginDo();
    }
    

}

