<?php
/** test Controler class generated by Prologics framework **/

class test extends controller {

    function __construct() {
        parent::__construct();

    }

    function index() {
    	$this->view->patientDetails = $this->model->viewPatientDetails();
        $this->view->load('test/index');
    }   

    function addPatientDetails(){
    	$data = array(
            'name' => $_POST['fullname'], 
            'age' => $_POST['age'], 
            'sex' => $_POST['sex'], 
            'diseases' => $_POST['diseases'], 
            'setdate' => date("Y-m-d h:i:sa")
        );
        $this->model->addPatientDetails($data);
    }

    function updatePatient($id){
        $this->view->patientEdit = $this->model->viewsinglePatient($id);
        $this->view->load('dashboard/edit');
    }

    function editPatient($id){
        $data = array(
            'id' => $id, 
            'name' => $_POST['fullname'], 
            'age' => $_POST['age'], 
            'sex' => $_POST['sex'], 
            'diseases' => $_POST['diseases'], 
            'setdate' => date("Y-m-d h:i:sa")
        );
        $this->model->editPatient($data);
    }

    function deletePatient($id){
        $this->model->deletePatient($id);
    }
    
    function log_out(){
        session::destroy();
        header("Location: " . URL . "index");
        exit;   
    }

    function searchDetails(){
        $this->view->searchSinglePatient = $this->model->searchDetails();
        $this->view->load('test/index');
    }

}

