<?php
/*
 *  error Model class Generated by Prologics Framework
 */

class error_model extends model{
    
    function __construct() {
        parent::__construct();
    }   
    
    
}

